config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "blog_posts#index"
  resources :blog_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  scope :draft, -> { where(published_at: nil, updated_at: :desc) }
  scope :published, -> { where('published_at <= ?', Time.current) }
  scope :scheduled, -> { where('published_at > ?', Time.current) }

  scope :sorted, -> { order(Arel.sql("published_at DESC NULLS LAST").order(updated_at: :desc)) }

  def draft?
    published_at.nil?
  end
  def published?
    published_at? && published_at <= Time.current
  end
  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, only: [:show, :edit, :destroy]
  def index
      @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
  end
  def show
    @blog_post = BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    root_path
  end
  def new
    @blog_post = BlogPost.new
  end
  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post, notice: 'Blog post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
  end
  def update
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post, notice: 'Blog post was successfully update.'
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @blog_post.destroy
    redirect_to root_path, notice: 'Blog post was successfully destroyed.'
  end
  private

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
  def blog_post_params
    params.require(:blog_post).permit(:title, :body, :published_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>

  <% if form.object.errors.any? %>
    <div id="error_explanation" class="error-messages">
      <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this blog post from being saved:</h2>
      <ul>
        <% form.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :published_at %><br>
    <%= form.datetime_select :published_at, include_blank: :true %>
  </div>

  <p>
    <%= form.submit 'Submit', class: 'bg-gray-100 py-2 px-4 rounded hover:bg-gray-200' %>
  </p>
<% end %>

app/views/blog_posts/edit.html.erb
<h1> Edit Blog Post </h1>

<%= render partial: 'form', locals: {blog_post: @blog_post} %>

<%= button_to 'Delete', @blog_post, method: :delete, data: {turbo_confirm: "Are you sure you want to delete?"} %>

app/views/blog_posts/index.html.erb
<h1>Blog Posts</h1>
<% @blog_posts.each do |post| %>
  <% if post.draft? %>
    <p class="p-2 rounded text-red-500">Draft</p>
  <% elsif post.scheduled? %>
    <p class="p-2 rounded text-yellow-500">Scheduled</p>
  <% end %>
  <h2><%= link_to post.title, blog_post_path(post) %></h2>
  <p><%= post.body %></p>
  <%# <p><%= link_to 'Show', blog_post_path(post) %>
  <%# <p><%= link_to 'Edit', edit_blog_post_path(post) %>
  <%# <p><%= link_to 'Destroy', blog_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
  <hr>
<% end %>

app/views/blog_posts/new.html.erb
<p>New Blog Post</p>

<%= render partial: 'form', locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<div class="blog-post">
  <h1 class="blog-post-title"><%= @blog_post.title %></h1>
  <p class="blog-post-body"><%= @blog_post.body %></p>

  <% if user_signed_in? %>
    <%= button_to 'Edit', edit_blog_post_path(@blog_post), class: "edit-button" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% if user_signed_in? %>
        <%= link_to "New Blog Post", new_blog_post_path %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% end %>

    <%= yield %>
  </body>
</html>